export const CODE_MESSAGE_AUTH_SUCCESS = 1;
export const CODE_MESSAGE_AUTH_FAIL = 2;
export const CODE_MESSAGE_SIGN_IN_SUCCESS = 3;
export const CODE_MESSAGE_SIGN_IN_FAIL = 4;
export const CODE_MESSAGE_SIGN_IN_INVALID_EMAIL_OR_PASSWORD = 5;

export const CODE_MESSAGE_SERVER_ERROR = 500;